### ISSUE TITLE
Proposal: Jekyll -> Gatsby

### ISSUE THREAD

**Issue by stedman** [austinjavascript/austinjavascript.com#105]
Sooo, perhaps it's time to bury the [cruel (Ruby) joke](https://github.com/austinjavascript/austinjavascript.github.io#previewing-changes) once and for all. While I realize there are probably some good reasons for sticking with Jekyll (online editing w/o need for local build/deploy step?), the GitHub ecosystem has evolved to such a place where we might be able to confidently move to a JavaScript-based publication solution.

As a first step, I thought I'd give the conversion from Jekyll to Gatsby a good old college try. The results of that effort can be found at https://stedman.github.io/ajs/ . A couple of notes:

* I tried to keep the good parts of the Jekyll post file naming convention. I extended it a bit to [have even more powers](https://github.com/stedman/ajs/blob/master/CONTRIBUTING.md#create-new-file) -- mostly to keep the YAML frontmatter as trim as possible.
* I migrated the 2019-2020 meetup files over as a starting point and added some fields.
* To keep things simple in the styling department, I went with the [Bulma CSS framework](https://bulma.io).
* I chose to adapt the current color palette as much as was tastefully possible. (Can someone explain `#ed1978`?)
* The home page can use a lot more love. The dynamically showing of upcoming events (as the current site does) still needs to be added.
* I still need to look into [GitHub Actions](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions) to replace Jekyll's auto recompiling.

Lastly, I know this is a huge change requiring careful consideration -- so I wanted to show rather than describe what the site could be. For this reason, I chose to start with a fresh repo and gh-pages site rather than branch off a fork of the existing AustinJS. If y'all like what you see and want to proceed, then I will figure out how to cross the streams.

**Comment by third774** [comment]
I'm super into this idea.

**Comment by aaronj1335** [comment]
Sounds great! We've wanted to switch to JS for a while. This started as Jekyll because it could deploy to GH Pages on push, and at the time I don't think there was good support for node in Travis, so here we are.

To me, the MVP would:

1. Deploy on push
1. Have a low page weight (I think it's currently ~100kb w/ resources)
1. Look good on mobile

Personally it seems like @11ty would be a better fit for this type of content, but whatever works!

**Comment by aaronj1335** [comment]
I guess the first requirement should really be that it's updateable on mobile. The idea being we should optimize for people looking at the page on their mobile devices on meetup day and organizers making last minute harried updates on meetup day.

**Comment by stedman** [comment]
@aaronj1335 I believe we can update (via mobile) like Jekyll/gh-pages on push with GitHub Actions, specifically something like https://github.com/marketplace/actions/gatsby-publish

I went with Gatsby in this case to provide a platform that more people are familiar with (React) -- to encourage more contribution. For the sake of contribution, I also chose a CSS Framework instead of hand-rolling the bits.

That said, the Gatsby/Bulma home page does come in at a rather hefty ~3MB. I'll look into @11ty and figure out the CSS weight tradeoffs.

**Comment by stedman** [comment]
FWIW, I assumed the following requirements (prioritized):

1. Maintain content parity with existing site
2. Maintain "post" contribution publication flow
  a. New meetup posts can be created with little training or effort
  b. Posts can be updated via mobile
3. Change tech stack from Ruby to Node
4. Make contribution to templates/pages easier

I didn't have performance on the list but agree it should be.

**Comment by stedman** [comment]
So I spent some time porting this to 11ty and the results look great. Thanks for the tip, @aaronj1335 . Home page size went down from 3.05MB to 458KB. I'll try to get this into a gh-pages branch ASAP and then work out the GH-Actions stuff.

https://github.com/stedman/ajs-11ty

**Comment by stedman** [comment]
UPDATE: the GitHub Actions/Workflow works! I was able to edit two posts via the GitHub online editor, make commits, and then see the updates on the live site.

The actions log is here: https://github.com/stedman/ajs-11ty/actions

**Comment by stedman** [comment]
Resolved by #122
