### ISSUE TITLE
October meetup

### ISSUE THREAD

**Issue by lawnsea** [austinjavascript/austinjavascript.com#61]
- [x] Speaker: @jkyle
- [x] Sponsor: eRelevance
- [x] Confirm venue
- [x] Meetup post
- [x] Blog post
- [x] Tweet
- [x] Order pizza
- [x] Record stats
- [ ] Invoice sponsor

**Comment by lawnsea** [comment]
@jkyle would you please post an abstract of your talk suitable for the blog post?

**Comment by jkyle** [comment]
@lawnsea feel free to edit as appropriate.

# How to Start a JavaScript Synthpop Band

Synthesizers! JavaScript! Aleatoricism?? Using an actual analog synthesizer as a guide, Kyle will build a feature-for-feature replica in the browser with the Web Audio API and show how to use JavaScript to overcome a lack of musical training. You'll learn the capabilities and limitations of the Web Audio API, and how it can be used for applications like gaming, WebVR, and 80s retro synthwave. With live coding, live synth playing, and a touch of music theory, _what could go wrong?_

# Our Speaker

![e-6bhcpn_400x400](https://user-images.githubusercontent.com/100188/31050212-9f8b34bc-a609-11e7-81dd-339b88c68800.jpg)


[J. Kyle Fagan](https://www.twitter.com/jkyle) is an Austin local and writes JavaScript for [Eduphoria](https://www.eduphoria.net). He's an aspirational artist, aspirational musician, and aspirational cool dad.

**Comment by rmurphey** [comment]
## pizza

eastside pies (512) 524-0933

- 2 pepperoni
- 1 pepperoni and mushroom
- 2 margherita
- 1 spinach, mushroom, black olive, and basil

double cut; ask for plates and napkins; deliver at 7:15

spredfast @ 200 w cesar chavez #300

## drinks

- 18 ipa
- 6 session ipa
- 6 oktoberfest
- 6 pale ale
- 6 wheat
- 6 stout
- 12 cider
- 4 topo
- 8 izzy

## notes

- more topo
