### ISSUE TITLE
September 2018 meetup

### ISSUE THREAD

**Issue by lawnsea** [austinjavascript/austinjavascript.com#76]
- [x]  Speaker: @adamgiese
- [x]  Sponsor: Cloudflare
- [x]  Confirm venue 
- [x]  Meetup post
- [x]  Blog post
- [x]  Tweet
- [x]  Order pizza
- [x]  Record stats
- [ ]  Invoice sponsor

**Comment by lawnsea** [comment]
@DrewML, here's the pizza order:
From East Side Pies Rosewood (512) 524-0933:
2 pepperoni
1 pepperoni and mushroom
1 margherita
1 spinach, mushroom, green bell pepper, black olive, and basil

all double cut
plates and napkins for 50
deliver at 7:15pm to 200 W Cesar Chavez St #300 (3rd floor)

**Comment by lawnsea** [comment]
[Reimbursement rules from Cloudflare](https://docs.google.com/document/d/1wvJjiS1iuzf_XYNaah20xTwNfjcBQeiqjmrHi9CEFWM/edit)
[Cloudflare slides](https://docs.google.com/presentation/d/1wDyFxApRVdXbxEyUYXJZl3plGeFMeAoFYSJtoclAUos/edit#slide=id.g310da0795c_0_6)

**Comment by DrewML** [comment]
🍕 order has been placed
