### ISSUE TITLE
April 2019 Meetup

### ISSUE THREAD

**Issue by lawnsea** [austinjavascript/austinjavascript.com#86]
- [x]  Speaker: @creationix
- [x]  Sponsor: magento
- [x]  Confirm venue 
- [x]  Meetup post
- [x]  Blog post
- [x]  Tweet
- [x]  Order pizza
- [ ]  Record stats
- [ ]  Invoice sponsor

**Comment by creationix** [comment]
JavaScript on microcontrollers.  I'll be showing how to program esp8266 chips using espruino.  Also will mention moddable.

**Comment by creationix** [comment]
I'll probably be doing some fancy rainbow animations on strips of neopixels.
