### ISSUE TITLE
July 2019 meetup

### ISSUE THREAD

**Issue by lawnsea** [austinjavascript/austinjavascript.com#89]
- [x]  Speaker: @nodebotanist
- [ ]  Sponsor: 
- [x]  Confirm venue
- [x]  Meetup post
- [x]  Blog post
- [x]  Tweet
- [ ]  Order pizza
- [ ]  Record stats
- [ ]  Invoice sponsor

**Comment by nodebotanist** [comment]
👍 I'll send a PR with a description soon.

**Comment by nodebotanist** [comment]
Web Assembly: What it Is, Why you should care, and what it means for JS

Let's talk about a five-year-old tech like it's brand new; which is really what WebAssembly is; it's been around for years but we're only just starting to discover what it can do and how to use it. I can say with no hyperbole that this is the next Ajax in terms of importance to browser applications, and in this talk I'll explain why a multi-language web doesn't spell the end of JavaScript but rather a Renaissance for the web.
